<a id="A"></a>
# <div style="text-align:center; border-radius:15px 50px; padding:20px; color:white; margin:0; font-size:150%; font-family:Pacifico; background-color:red; overflow:hidden"><b> Numpy Practice Questions </b></div>



<a id="2"></a>
# <div style="text-align:center; border-radius:15px 30px; padding:10px; color:white; margin:0; font-size:100%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 🌟 About Author 🌟 </b></div>

<div style="background-color: white; border: 9px solid black; border-radius: 19px; box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1); max-width: 600px; margin: 20px auto; padding: 20px; text-align: center; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;">
    <h2 style="color: black; font-weight: bold; margin-bottom: 10px;">WAQAR ALI</h2>
    <p style="font-size: 16px; line-height: 1.6; color: black; margin-bottom: 20px;">
        I'm a passionate Data Scientist and Analyst, dedicated to transforming raw data into actionable insights through captivating visualizations. Let's dive into the fascinating world of data and uncover the stories hidden within! 📊🔍✨
    </p>
</div>


<a id="A"></a>
# <div style="text-align:center; border-radius:15px 30px; padding:10px; color:white; margin:0; font-size:100%; font-family:Pacifico; background-color:red; overflow:hidden"><b> Basic Problems </b></div>



<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 1. Create a 1D array with numbers from 1 to 10. </b></div>



In [1]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 2. Create a 2D array with 2 rows and 3 columns, where all elements are 5. </b></div>



In [2]:
import numpy as np
arr = np.array([[5,5,5],[5,5,5]])
arr

array([[5, 5, 5],
       [5, 5, 5]])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 3. Create an array with even numbers from 1 to 20. </b></div>



In [3]:
import numpy as np
arr = np.arange(1,21)
arr[1:20:2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 4.Create an array with odd numbers from 1 to 15. </b></div>



In [4]:
import numpy as np
arr = np.arange(1,16)
arr[0:15:2]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 5. Create an array with numbers from 1 to 100. Print the first 20 elements. </b></div>



In [5]:
import numpy as np
arr = np.arange(1,101)
arr[0:20]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 6. Create an array with numbers from 1 to 50. Print the last 10 elements. </b></div>



In [6]:
import numpy as np
arr = np.arange(1,51)
arr[40:51]

array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 7. Create an array with numbers from 1 to 30. Print all even-indexed elements. </b></div>



In [7]:
import numpy as np
arr = np.arange(1,31)
arr[0:30:2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 8. Create an array with numbers from 1 to 25. Print all odd-indexed elements. </b></div>



In [8]:
import numpy as np
arr = np.arange(1,26)
arr[1:25:2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 9. Create an array with numbers from 1 to 10. Calculate the square of all elements. </b></div>



In [9]:
import numpy as np
arr = np.arange(1,11)
ar = arr*arr
ar

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 10. Create an array with numbers from 1 to 10. Calculate the cube of all elements. </b></div>



In [10]:
import numpy as np
arr = np.arange(1,11)
ar = arr*arr*arr
ar

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 11. Create an array with numbers from 1 to 20. Calculate the sum of all elements. </b></div>



In [11]:
import numpy as np
arr = np.arange(1,21)
np.sum(arr)

210

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 12. Create an array with numbers from 1 to 20. Calculate the product of all elements. </b></div>



In [12]:
import numpy as np
arr = np.arange(1,21)
np.product(arr)

2432902008176640000

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 13. Create an array with 100 random numbers between 1 and 100. Calculate the mean of the array. </b></div>



In [13]:
import numpy as np
arr = np.random.randint(1,101, size=100)
print(arr)
arr.mean()

[ 54  16  23  45  82  50  56  38  12  42  16  63  84  59   1  36  18  72
  38 100  48  30  83  58  88  95  89  95  19  18   6  25  65  79  69  45
  55   9  59  10   1  84  34  62  48  72  82  30  47  14  59  97  68  71
  48  27  28  85   7   4  91  54  36  65  39  10  26  60  45  83  86  66
  75  33  38  48   6  59  20  18  42  76  11  79  57  55  36  96  69  69
  75  99   2  27  45  27  57  19  13  94]


49.24

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 14. Create an array with 100 random numbers between 1 and 100. Calculate the median of the array. </b></div>



In [14]:
import numpy as np
arr = np.random.randint(1,101,size=100)
np.median(arr)

44.5

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 15. Create an array with 100 random numbers between 1 and 100. Calculate the standard deviation of the array. </b></div>



In [15]:
import numpy as np
arr = np.random.randint(1,101,size=100)
arr.std()

28.864400218954835

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 16. Create an array with 100 random numbers between 1 and 100. Calculate the variance of the array. </b></div>



In [16]:
import numpy as np
arr = np.random.randint(1,101,size=100)
arr.var()

799.6475

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 17. Create an array with numbers from 1 to 50. Sort the array in ascending order. </b></div>



In [17]:
import numpy as np
arr = np.arange(1,51)
arr.sort()
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 18. Create an array with numbers from 1 to 50. Sort the array in descending order. </b></div>



In [18]:
import numpy as np
arr = np.arange(1,51)
arr[::-1]

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 19. Create an array with 100 random numbers between 1 and 100. Print all unique elements. </b></div>



In [19]:
import numpy as np
arr = np.random.randint(1,101,size=100)
np.unique(arr)

array([ 1,  2,  3,  4,  6,  7,  8, 10, 11, 12, 13, 14, 16, 19, 21, 22, 23,
       28, 29, 30, 32, 33, 35, 37, 38, 39, 40, 41, 42, 45, 46, 48, 53, 54,
       56, 59, 62, 64, 66, 67, 68, 69, 72, 73, 74, 76, 79, 80, 82, 83, 86,
       87, 88, 89, 93, 94, 95, 96, 97])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 20. Create an array with 100 random numbers between 1 and 100. Print all duplicate elements. </b></div>



In [20]:
import numpy as np
random_numbers = np.random.randint(1, 101, size=100)
unique_elements, counts = np.unique(random_numbers, return_counts=True)
duplicates = unique_elements[counts > 1]
print(unique_elements)
print(duplicates)

[ 1  2  3  7  8  9 10 11 12 13 14 15 19 20 21 24 25 26 27 29 30 32 33 34
 35 38 39 42 44 45 47 48 49 50 51 52 54 56 58 63 65 66 67 68 70 71 73 76
 77 79 81 82 84 85 87 89 90 91 95 97 98 99]
[ 2  3  9 12 21 25 34 35 39 47 48 49 50 51 52 54 58 71 73 76 77 81 87 90
 91 95 97]


<a id="A"></a>
# <div style="text-align:center; border-radius:15px 30px; padding:10px; color:white; margin:0; font-size:100%; font-family:Pacifico; background-color:red; overflow:hidden"><b> Intermediate Problems </b></div>



<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 21. Create a 1D array with numbers from 1 to 25. Reshape it into a 5x5 matrix. </b></div>



In [21]:
import numpy as np
arr = np.arange(1,26)
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 22. Create a 2D array with 3 rows and 3 columns, where each element is equal to its row index. </b></div>



In [22]:
import numpy as np
array = np.full((3, 3), np.arange(3).reshape(3, 1))
print(array)


[[0 0 0]
 [1 1 1]
 [2 2 2]]


<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 23. Create a 2D array with 4 rows and 4 columns, where each element is equal to its column index. </b></div>



In [23]:
import numpy as np 
array = np.full((4, 4), np.arange(4))
array


array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 24. Create a 2D array with 3 rows and 3 columns, where each element is the sum of its row and column indices. </b></div>


In [24]:
import numpy as np
rows,columns = np.indices((3,3))
array = rows + columns 
array

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 25. Create a 2D array with 3 rows and 3 columns, where each element is the product of its row and column indices. </b></div>


In [25]:
import numpy as np
rows,columns = np.indices((3,3))
array = rows * columns
array

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 26. Create a 2D array with 3 rows and 3 columns. Add 10 to all elements using broadcasting. </b></div>


In [26]:
import numpy as np
arr = np.array([[0,0,0],[0,0,0],[0,0,0]])
ar = arr + 10
ar

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 27. Create a 2D array with 3 rows and 3 columns. Multiply all elements by 2. </b></div>


In [27]:
import numpy as np
arr = np.array([[1,1,1],[1,1,1],[1,1,1]])
ar = arr * 2
ar

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 28. Create a 2D array with 3 rows and 3 columns. Divide all elements by 5. </b></div>


In [28]:
import numpy as np
arr = np.array([[10,10,10],[20,20,20],[30,30,30]])
ar = arr / 5
ar

array([[2., 2., 2.],
       [4., 4., 4.],
       [6., 6., 6.]])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 29. Create a 2D array with 3 rows and 3 columns. Calculate the square root of all elements. </b></div>


In [29]:
import numpy as np
arr = np.array([[4,4,4],[9,9,9],[16,16,16]])
np.sqrt(arr)

array([[2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 30. Create a 2D array with 3 rows and 3 columns. Calculate the natural logarithm of all elements. </b></div>


In [30]:
import numpy as np
arr = np.array([[4,4,4],[9,9,9],[16,16,16]])
ar = np.log(arr)
ar

array([[1.38629436, 1.38629436, 1.38629436],
       [2.19722458, 2.19722458, 2.19722458],
       [2.77258872, 2.77258872, 2.77258872]])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 31. Create a 2D array with 3 rows and 3 columns. Calculate the exponential of all elements. </b></div>


In [31]:
import numpy as np
arr = np.array([[4,4,4],[9,9,9],[16,16,16]])
ar = np.exp(arr)
ar

array([[5.45981500e+01, 5.45981500e+01, 5.45981500e+01],
       [8.10308393e+03, 8.10308393e+03, 8.10308393e+03],
       [8.88611052e+06, 8.88611052e+06, 8.88611052e+06]])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 32. Create a 2D array with 3 rows and 3 columns. Replace all diagonal elements with 1. </b></div>


In [32]:
import numpy as np
arr = np.array([[4,4,4], [9,9,9], [16,16,16]])
np.fill_diagonal(arr, 1)
arr  


array([[ 1,  4,  4],
       [ 9,  1,  9],
       [16, 16,  1]])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 33. Create a 2D array with 3 rows and 3 columns. Calculate the transpose of the array. </b></div>


In [33]:
import numpy as np
arr = np.array([[4,4,4], [9,9,9], [16,16,16]])
arr.T

array([[ 4,  9, 16],
       [ 4,  9, 16],
       [ 4,  9, 16]])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 34. Create a 2D array with 3 rows and 3 columns. Calculate the determinant of the array. </b></div>


In [34]:
import numpy as np
arr = np.random.randint(1,10,(3,3))
print(arr)
np.linalg.det(arr)

[[9 2 2]
 [7 2 9]
 [1 3 1]]


-183.00000000000009

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 35. Create a 2D array with 3 rows and 3 columns. Calculate the inverse of the array. </b></div>


In [35]:
import numpy as np
arr = np.random.randint(1,10,(3,3))
np.linalg.inv(arr)

array([[-0.03846154,  0.13461538, -0.01923077],
       [ 0.25      , -0.125     , -0.125     ],
       [-0.40384615,  0.16346154,  0.54807692]])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 36. Create a 2D array with 3 rows and 3 columns. Calculate the rank of the array. </b></div>


In [36]:
import numpy as np
arr = np.random.randint(1,10,(3,3))
np.linalg.matrix_rank(arr)

3

<a id="A"></a>
# <div style="text-align:center; border-radius:15px 30px; padding:10px; color:white; margin:0; font-size:100%; font-family:Pacifico; background-color:red; overflow:hidden"><b> Advanced Problems </b></div>



<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 37. Create a 3D array with 2 layers, 3 rows, and 4 columns. </b></div>


In [37]:
import numpy as np
arr = np.random.randint(1,10, (2,3,4))
arr

array([[[9, 7, 1, 9],
        [6, 4, 3, 3],
        [3, 9, 1, 8]],

       [[9, 9, 4, 1],
        [8, 1, 3, 4],
        [7, 8, 6, 5]]])

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 38. Create a 3D array with 3 layers, 2 rows, and 2 columns. Calculate the sum of all elements. </b></div>


In [38]:
import numpy as np
arr = np.random.randint(1,10, (3,2,2))
arr.sum()

69

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 39. Create a 3D array with 3 layers, 2 rows, and 2 columns. Calculate the mean of all elements. </b></div>


In [39]:
import numpy as np
arr = np.random.randint(1,10, (3,2,2))
arr.mean()

5.916666666666667

<a id="A"></a>
# <div style="text-align:center; border-radius:5px 10px; padding:5px; color:white; margin:0; font-size:70%; font-family:Pacifico; background-color:black; overflow:hidden"><b> 40. Create a 3D array with 3 layers, 2 rows, and 2 columns. Find the maximum value in the array. </b></div>


In [40]:
import numpy as np
arr = np.random.randint(1,10, (3,2,2))
arr.max()

9

<div style="font-size: 30px; color: white; text-align: center; margin-top: 20px; padding: 10px; border: 5px solid white; background-color: red; border-radius: 10px;">
    <p style="font-weight: bold; margin: 0; display: inline-block;">Notebook Created by Waqar Ali</p>
    <br>
    <p style="font-weight: bold; margin: 0; display: inline-block;">Created on: March 1, 2025</p>
</div>


<div style="font-size: 50px; font-weight: bold; color: white; text-transform: uppercase; background-color: red; border: 5px solid white; padding: 5px 10px; display: inline-block; border-radius: 10px; width: 750px; text-align: center; margin: 0 auto; display: block;">
    Thank You   
</div>